### ISSUE TITLE
线程等待与通知关于wait()方法的解释有误

### ISSUE THREAD

**Issue by Unsurefeedback** [itwanger/toBeBetterJavaer#105]
在Java并发编程第五题，线程 A 会被阻塞挂起后，应该是其它线程调用对象的notify（)或者notifyAll方法来唤醒线程A，网站上写的是【线程 A 会被阻塞挂起，直到发生下面几种情况才会返回 ：线程 A 调用了共享对象 notify()或者 notifyAll() 方法；】

**Comment by itwanger** [comment]
已经优化，感谢指正。
