### ISSUE TITLE
《面渣逆袭-Redis》-Redis 持久化方式中关于 AOF 的刷盘策略描述有误

### ISSUE THREAD

**Issue by imlyk** [itwanger/toBeBetterJavaer#106]
<img width="1503" alt="这个错了吧" src="https://github.com/itwanger/toBeBetterJavaer/assets/35001769/144f1c45-c45d-457e-b78b-82f86f0bf091">

这里可能丢失一秒数据应该是 everysec 这种刷盘策略的吧？

**Comment by itwanger** [comment]
新版本中已经优化，感谢指正。
