### ISSUE TITLE
jsDelivr撤出国内节点,导致部分图片不显示或者加载缓慢

### ISSUE THREAD

**Issue by yzqdev** [itwanger/toBeBetterJavaer#12]
### 由于jsDelivr撤出国内节点,部分地区使用jsDelivr托管的静态图片加载缓慢,时常需要一两分钟才能加载出来

![image](https://user-images.githubusercontent.com/20037151/154095485-18445177-500b-4b14-a14f-c56fc8dc0bf9.png)

**Comment by itwanger** [comment]
我擦，这个问题就影响大了呀

**Comment by yzqdev** [comment]
似乎已经恢复了

**Comment by itwanger** [comment]
已经替换了 CDN + OSS，现在应该飞快了。

**Comment by yzqdev** [comment]
谢谢大佬,大佬费心了😃
