### ISSUE TITLE
hashMap 中的 hash 原理处 

### ISSUE THREAD

**Issue by yp2020** [itwanger/toBeBetterJavaer#13]
理论上，哈希值是一个 int 类型，范围从-2147483648 到 2147483648。前后加起来大概 40 亿的映射空间，只要哈希值映射得比较均匀松散，一般是不会出现哈希碰撞的。

建议范围加上 左闭右开。
因为 int 类型为 4字节，也就是 32位，取值范围为 [-2^31,2^31-1]。也就是 -2147483648 到 2147483647

**Comment by itwanger** [comment]
请给我一个点赞的机会。

**Comment by ChenJie6411643** [comment]
您好，关于 【44.BIO、NIO、AIO？】一节中，图片内容有两处是NIO，请问最后的一个NIO是否为AIO？

**Comment by itwanger** [comment]
已在文章中追加你的建议，谢谢
