### ISSUE TITLE
tobebetterjavaer.com网站代码复制功能无效

### ISSUE THREAD

**Issue by leo220yuyaodog** [itwanger/toBeBetterJavaer#18]
![image](https://user-images.githubusercontent.com/71440988/169750124-8053604d-22ac-4e70-8876-e0880df35cef.png)
浏览器: microsoft   
网站 vuepress版 
位置  https://tobebetterjavaer.com/thread/thread-state-and-method.html#java%E7%BA%BF%E7%A8%8B%E7%9A%846%E4%B8%AA%E7%8A%B6%E6%80%81
问题：如标题，点击复制代码后，没有实际功能，无法复制代码

**Comment by itwanger** [comment]
等我用 microsoft 试一下，你是指 IE 还是 edge？

**Comment by leo220yuyaodog** [comment]
> 等我用 microsoft 试一下，你是指 IE 还是 edge？
现在没问题了，谢谢哈。已经进关掉了
![image](https://user-images.githubusercontent.com/71440988/172147191-d86c5120-3e5f-43d2-892e-3daa028ccd8e.png)
当时是提示语太靠上了，我已为没有响应。功能是ok的

**Comment by itwanger** [comment]
OK
