### ISSUE TITLE
赠人玫瑰，手有余香，感谢分享，您的网站有编辑错误，给您指出啦！

### ISSUE THREAD

**Issue by harmonIT** [itwanger/toBeBetterJavaer#22]

**Comment by wenbin0** [comment]
![屏幕截图 2022-07-16 151111](https://user-images.githubusercontent.com/89673821/179344629-35503b63-9be3-44b2-be23-7e7e30cf6d9c.jpg)

**Comment by wenbin0** [comment]
初学Java，楼主很厉害，欢迎光顾我的博客
https://www.cnblogs.com/ZiShaoYouWo/

**Comment by itwanger** [comment]
笔芯

**Comment by itwanger** [comment]
确认了一下，没有错误啊。
