### ISSUE TITLE
简述Executor的继承关系：ThreadPoolExecutor：继承ThreadPoolExecutor

### ISSUE THREAD

**Issue by atgtahub** [itwanger/toBeBetterJavaer#32]
https://tobebetterjavaer.com/interview/java-thread-baguwen.html#%E7%AE%80%E8%BF%B0executor%E7%9A%84%E7%BB%A7%E6%89%BF%E5%85%B3%E7%B3%BB
应为：ScheduledThreadPoolExecutor继承ThreadPoolExecutor
![image](https://user-images.githubusercontent.com/53530286/208858982-87a0aa67-1150-4884-8392-37805c453316.png)

**Comment by itwanger** [comment]
感谢指正，已经修复。
