### ISSUE TITLE
2.5集合框架 LinkedList详解

### ISSUE THREAD

**Issue by LookSin** [itwanger/toBeBetterJavaer#33]
- remove()删除第一个节点
- removeFirst()删除第一个节点
------------------------------------------------
有一个疑惑的点，remove()应该是删除指定节点吧。

**Comment by LookSin** [comment]
![image](https://user-images.githubusercontent.com/109679879/209266444-a658b00c-6f29-4b84-afce-875c3d6d6bb6.png)

**Comment by CompetitiveLin** [comment]
![image](https://user-images.githubusercontent.com/55691019/209339882-c7a32871-92c5-4f3f-bd72-3a5d4b8dd9d7.png)
[Here](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedList.html)

**Comment by LookSin** [comment]
OK. Thank you for your answer.
