### ISSUE TITLE
一个小错误

### ISSUE THREAD

**Issue by yp2020** [itwanger/toBeBetterJavaer#36]
![image](https://user-images.githubusercontent.com/64645863/210288513-5cd5946e-0c16-4125-9b08-e24fadd60753.png)
[原链接如下](https://tobebetterjavaer.com/oo/method.html#_06%E3%80%81%E4%BB%80%E4%B9%88%E6%98%AF%E6%8A%BD%E8%B1%A1%E6%96%B9%E6%B3%95)

**Comment by itwanger** [comment]
感谢指正，已经修正。
