### ISSUE TITLE
Arrays.asList()把数组转list

### ISSUE THREAD

**Issue by rechargeableSophy** [itwanger/toBeBetterJavaer#38]
![image](https://user-images.githubusercontent.com/97727390/210337978-299ee0e0-6dcf-4ce0-9775-d0fe06e5aab9.png)
![image](https://user-images.githubusercontent.com/97727390/210338010-3b3099e4-598c-46b7-9a39-3122cf2fe6f8.png)
如图，这里数组设置为int[]时候，转成List<Integer>会报错，但是如果数组设置为Integer[],没有报错，版本是jdk1.8

**Comment by itwanger** [comment]
是需要 Integer 的，不能是基本数据类型，而应该是包装器类型。
