### ISSUE TITLE
发现了一个小 bug（数组转 List）

### ISSUE THREAD

**Issue by itwanger** [itwanger/toBeBetterJavaer#59]
1、链接：https://tobebetterjavaer.com/array/array.html
2、错误处（可截图）：
<img width="779" alt="image" src="https://user-images.githubusercontent.com/6011374/220518400-73f9dd6e-3a7c-41a7-b35e-1befe6dc43b1.png">
3、描述：

```
Arrays.asList的目标只能是对象，Arrays.asList(int[] arr)是不行的，必须是Arrays.asList(Integer[] arr)才能成功赋给List
int[] 转 Integer[] 可以用 Arrays.stream(arr).boxed().toArray(Integer[]::new)
Java这个装箱机制用起来让我真的自闭，C#就不会这么折磨，可惜C#吕布骑狗。。。
```

**Comment by EvanHsieh0415** [comment]
補充：Source [`./docs/array/array.md #L176-L182`](../blob/master/docs/array/array.md?plain=1#L176-L182)

**Comment by itwanger** [comment]
新版本已经加了新的说明，感谢勘误。
