### ISSUE TITLE
javase中第38点Object类 wait(long timeout,int nanos)描述错误

### ISSUE THREAD

**Issue by xuyuechi** [itwanger/toBeBetterJavaer#67]
timeout的单位是毫秒，nanos的单位是纳秒

**Comment by xuyuechi** [comment]
面渣逆袭，java基础篇
https://github.com/itwanger/toBeBetterJavaer/tree/master/docs/sidebar/sanfene/javase.md

**Comment by itwanger** [comment]
新版本已经修复。
