### ISSUE TITLE
Redis 有哪些数据结构？这个回答有问题

### ISSUE THREAD

**Issue by shubiaodian** [itwanger/toBeBetterJavaer#71]
Redis 的数据结构应该是指SDS、链表、字典、跳跃表、整数集合、压缩列表。至于字符串、哈希、列表、集合、有序集合是基于这些数据结构实现的对象或者应用。类比：B+树和索引。索引可以通过B+树这种数据结构实现，但索引不能叫数据结构

**Comment by itwanger** [comment]
OK，你的认知是正确的。已经改为数据类型，这样就更加合适一点。
