### ISSUE TITLE
这里的注释是否错误

### ISSUE THREAD

**Issue by FLYXH** [itwanger/toBeBetterJavaer#73]
![9df98d63de3c303d26788d4a79189f8](https://user-images.githubusercontent.com/34016138/236597745-43e82f0d-5bd8-428e-b511-f60b98829011.png)

应该为: 当符合条件的时候,生产者阻塞,释放锁, 等待被消费者唤醒;
同理,下面的消费者的注释应该也不对

**Comment by itwanger** [comment]
新版已经优化和修改。
