### ISSUE TITLE
注释不正确

### ISSUE THREAD

**Issue by FLYXH** [itwanger/toBeBetterJavaer#74]
public void put(E e) throws InterruptedException {
    checkNotNull(e);
    final ReentrantLock lock = this.lock;
    lock.lockInterruptibly();
    try {
		//如果当前队列已满，将线程移入到notFull等待队列中
        while (count == items.length)
            notFull.await();
		//满足插入数据的要求，直接进行入队操作
        enqueue(e);
    } finally {
        lock.unlock();
    }
}

注释不正确: //如果当前队列已满，将线程移入到notFull等待队列中 条件满足后,让notfull线程等待

**Comment by itwanger** [comment]
OK，已经修复了。感谢指正。
