### ISSUE TITLE
[2.5Java泛型，深入解析]表述错误

### ISSUE THREAD

**Issue by testlogo** [itwanger/toBeBetterJavaer#79]
举个例子，假设有一个类 Animal，以及两个子类 Dog 和 Cat。现在我们有一个 List<? super Dog> 集合，它的类型参数必须是 Dog 或其父类类型。我们可以向该集合中添加 Dog 类型的元素，也可以添加它的**子类**。但是，不能向其中添加 Cat 类型的元素，因为 Cat 不是 Dog 的**子类**。这里应该是父类。

**Comment by itwanger** [comment]
不，我的描述应该是正确的，你可以再试试。super 加通配符就是限定参数是子类或者本身。
