### ISSUE TITLE
面渣逆袭javaee里Java数据类型的图有错误

### ISSUE THREAD

**Issue by github2474** [itwanger/toBeBetterJavaer#88]
1. 整数型少了int和long，浮点类型long标错应该是double。

2.下面的引用数据类型可以加上枚举类型

**Comment by itwanger** [comment]
新版本已经修复，感谢指正。

**Comment by github2474** [comment]
客气了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月13日(星期六) 上午10:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [itwanger/toBeBetterJavaer] 面渣逆袭javaee里Java数据类型的图有错误 (Issue #88)














 
新版本已经修复，感谢指正。
