### ISSUE TITLE
Java基础里面Java反射文章有一处错误

### ISSUE THREAD

**Issue by Yjx710** [itwanger/toBeBetterJavaer#91]
这里是介绍获取字段，应该是getField，文章里面的是getMethod获取方法，特指出
![image](https://github.com/itwanger/toBeBetterJavaer/assets/55580717/667e8ec7-736d-4b4f-8e34-f20638a448a4)

应该是

`
Field[] fields = System.class.getFields();
`
`
Field field = System.class.getField("out");
`

**Comment by itwanger** [comment]
OK，感谢，已经修复。
