### ISSUE TITLE
文章描述错误-synchronized的四种锁状态

### ISSUE THREAD

**Issue by tianyuxingxuan** [itwanger/toBeBetterJavaer#95]
作者你好，你在synchronized的四种锁状态 这篇文章中关于重量级锁的描述有一处错误，“这是因为对于重量级锁，线程需要先自旋尝试获得锁”，重量级锁不会自旋，他会立即获取锁，如果没有获取到，就会立即进入阻塞状态。并不会自旋。思考下，如果他会自旋，那他和轻量级锁有什么区别了呢？

**Comment by itwanger** [comment]
此处描述有误，新版本已经修正。
